/* Episode viewer — section 12, "Watch one run, second by second".
 *
 * Vanilla ES2020 module, no dependencies, no network beyond two JSON files that
 * ship with the page. It progressively enhances the markup generated by
 * build/make_viewer_partial.py: without this file the section is still two
 * videos with their WebVTT captions, their chapter track and a written summary.
 *
 * The one rule that matters in here
 * --------------------------------
 * Every time in eN.json — events, lanes, tokens, chapters — is RUN time on the
 * overhead recording. The file being played is not always on that clock: e2 is
 * encoded at 2x, so run 600 s is video 300 s. Convert with runToVideo() before
 * touching video.currentTime and with videoToRun() before highlighting
 * anything. Nothing else in this file may read currentTime directly.
 *
 * Clocks on screen are always the run clock. The page's completion-time metric
 * (a different convention, ending at the report-writing boundary) is not shown
 * by this module at all; it appears only inside the prepared caption copy.
 *
 * Talks to the rest of the page through two document events:
 *   dispatches "agp:viewer-play"  when an episode starts playing
 *   listens for "agp:pause-all"   and pauses
 */

/* Three stills in the two episodes show a demonstrator's bare hand and forearm
 * (privacy.hand_in_frame in each JSON). 'gate' keeps them behind one click with
 * the reason stated; 'hide' drops them from the filmstrip entirely; 'show'
 * treats them like any other still. Change this one constant if the privacy
 * sign-off decides differently. */
const HAND_POLICY = 'gate';

const LANES = [
  { key: 'model',   name: 'Model generating', short: 'Model',    kind: 'span',  colour: 'var(--ev-model)' },
  { key: 'tool',    name: 'Tool runs',        short: 'Tools',    kind: 'span',  colour: 'var(--ev-tool)' },
  { key: 'motion',  name: 'Robot motion',     short: 'Motion',   kind: 'span',  colour: 'var(--ev-motion)' },
  { key: 'capture', name: 'Camera captures',  short: 'Captures', kind: 'point', colour: 'var(--ev-capture)' },
  { key: 'look',    name: 'Images viewed',    short: 'Images',   kind: 'point', colour: 'var(--ev-look)' },
  { key: 'say',     name: 'Agent messages',   short: 'Messages', kind: 'point', colour: 'var(--ev-say)' }
];

const reduceMotion = window.matchMedia
  ? window.matchMedia('(prefers-reduced-motion: reduce)')
  : { matches: false };

/* ── small helpers ──────────────────────────────────────────────────────── */

const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}

/** m:ss on the run clock. */
function mmss(t) {
  const s = Math.max(0, Math.round(t));
  return Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0');
}

/** "8 min 33 s", for screen-reader value text. */
function spoken(t) {
  const s = Math.max(0, Math.round(t));
  const m = Math.floor(s / 60);
  return (m ? m + ' min ' : '') + (s % 60) + ' s';
}

function num(v, places) {
  return Number(v).toFixed(places);
}

function el(tag, cls, html) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (html != null) n.innerHTML = html;
  return n;
}

/** A lane name that shrinks to one word on a narrow screen. */
function laneName(lane) {
  return '<span class="ev-swatch" style="background:' + lane.colour + '"></span>' +
    '<span class="ev-lane-long">' + esc(lane.name) + '</span>' +
    '<span class="ev-lane-short">' + esc(lane.short) + '</span>';
}

/** Index of the last item with time <= t, or -1. `times` must be sorted. */
function lastAtOrBefore(times, t) {
  let lo = 0, hi = times.length - 1, out = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (times[mid] <= t) { out = mid; lo = mid + 1; } else { hi = mid - 1; }
  }
  return out;
}

/* ── one episode ────────────────────────────────────────────────────────── */

class Episode {
  constructor(root, viewer) {
    this.root = root;
    this.viewer = viewer;
    this.id = root.dataset.ep;
    this.video = root.querySelector('.ev-video');
    this.speed = parseFloat(root.dataset.speed) || 1;          // video speed-up
    this.from = parseFloat(root.dataset.from) || 0;            // run s at video 0
    this.duration = parseFloat(root.dataset.duration) || 0;    // run s, full
    this.playable = parseFloat(root.dataset.playable) || this.duration;
    this.videoDuration = parseFloat(root.dataset.videoDuration) || 0;
    this.imgDir = root.dataset.imgDir || '';
    this.burninLead = parseFloat(root.dataset.burninLead) || 0;
    this.data = null;
    this.built = false;
    this.follow = true;
    this.filmFollow = true;
    this.revealed = new Set();
    this.runT = 0;
    this.rafId = 0;
  }

  /* time map — the only two places the two clocks meet */
  runToVideo(t) { return (t - this.from) / this.speed; }
  videoToRun(v) { return this.from + v * this.speed; }

  get maxVideoT() {
    const hard = this.video.duration || this.videoDuration || Infinity;
    return Math.min(this.runToVideo(this.playable), hard);
  }

  async load() {
    if (this.data) return this.data;
    const url = this.root.dataset.json;
    const res = await fetch(url, { credentials: 'same-origin' });
    if (!res.ok) throw new Error('viewer data ' + url + ' failed: ' + res.status);
    this.data = await res.json();
    return this.data;
  }

  /* ---- build --------------------------------------------------------- */

  build() {
    if (this.built) return;
    const d = this.data;
    this.built = true;

    this.imgByIndex = new Map();
    this.imgByName = new Map();
    d.images.forEach((im) => {
      this.imgByIndex.set(im.i, im);
      this.imgByName.set(im.name, im);
    });
    this.gated = new Set(
      HAND_POLICY === 'show' ? [] : (d.privacy && d.privacy.hand_in_frame) || []
    );

    this.buildTransport();
    this.buildStrip();
    this.buildRail();
    this.buildFilm();
    this.wireChapterList();

    this.video.removeAttribute('controls');
    this.video.addEventListener('play', () => this.onPlay());
    this.video.addEventListener('pause', () => this.onPause());
    this.video.addEventListener('ended', () => this.onPause());
    this.video.addEventListener('seeked', () => this.tick(true));
    this.video.addEventListener('timeupdate', () => { if (this.video.paused) this.tick(true); });
    this.video.addEventListener('loadedmetadata', () => this.tick(true));

    this.setCaptions(true);
    this.tick(true);
  }

  buildTransport() {
    const mount = this.root.querySelector('[data-mount="transport"]');
    mount.innerHTML = '';

    this.playBtn = el('button', 'ev-btn ev-btn--play', 'Play');
    this.playBtn.type = 'button';
    this.playBtn.addEventListener('click', () => this.togglePlay());
    mount.appendChild(this.playBtn);

    [['− 10 s', -10], ['+ 10 s', 10]].forEach(([label, dt]) => {
      const b = el('button', 'ev-btn', label);
      b.type = 'button';
      b.setAttribute('aria-label', (dt < 0 ? 'Back ' : 'Forward ') + Math.abs(dt) + ' seconds');
      b.addEventListener('click', () => this.seekRun(this.runT + dt, true));
      mount.appendChild(b);
    });

    this.clock = el('span', 'ev-clock');
    this.clock.setAttribute('aria-live', 'off');
    mount.appendChild(this.clock);

    this.capBtn = el('button', 'ev-btn', 'Captions on');
    this.capBtn.type = 'button';
    this.capBtn.setAttribute('aria-pressed', 'true');
    this.capBtn.addEventListener('click', () => this.setCaptions(!this.captionsOn));
    mount.appendChild(this.capBtn);

    const link = el('button', 'ev-btn',
      'Copy link<span class="ev-btn-more"> to this moment</span>');
    link.type = 'button';
    link.addEventListener('click', () => this.copyLink(link));
    mount.appendChild(link);

    const wrap = el('span', 'ev-speed');
    const sel = el('select');
    sel.id = 'ev-speed-' + this.id;
    [0.5, 1, 2].forEach((rate) => {
      const o = document.createElement('option');
      o.value = String(rate);
      const eff = rate * this.speed;
      o.textContent = (Number.isInteger(eff) ? eff : eff.toFixed(1)) + '×';
      if (rate === 1) o.selected = true;
      sel.appendChild(o);
    });
    sel.addEventListener('change', () => { this.video.playbackRate = parseFloat(sel.value); });
    const lab = el('label', null, 'Speed');
    lab.setAttribute('for', sel.id);
    wrap.appendChild(lab);
    wrap.appendChild(sel);
    mount.appendChild(wrap);

    if (this.burninLead) {
      const note = el('p', 'ev-clocknote',
        'The clock in the corner of the frame runs ' + num(this.burninLead, 1) +
        ' s ahead of this one: it starts when the task was handed over, this one ' +
        'when the recording did.');
      mount.parentNode.insertBefore(note, mount.nextSibling);
      this.clockNote = note;
    }
  }

  /** The written chapter list under the summary is the strip's table view;
   *  with the script running it also seeks. */
  wireChapterList() {
    const rows = this.root.querySelectorAll('.ev-chlist > li');
    rows.forEach((li, i) => {
      const c = this.data.chapters[i];
      if (!c) return;
      const b = el('button', 'ev-chbtn');
      b.type = 'button';
      while (li.firstChild) b.appendChild(li.firstChild);
      b.addEventListener('click', () => this.seekRun(c.t, true));
      li.appendChild(b);
    });
  }

  /** Show a chapter title only where the whole title fits inside its button.
   *  A button is as wide as its chapter is long, so which titles fit changes with the
   *  page width; every title stays on the button as its accessible name, and all six
   *  are spelled out in the Chapters list under the episode. */
  fitChapters() {
    if (!this.chapBtns || !this.chapBar || !this.chapBar.clientWidth) return;
    this.chapBtns.forEach((b) => {
      const title = b.querySelector('.ev-chap-title');
      if (!title) return;
      b.classList.add('ev-chap--wide');
      title.hidden = false;
      if (b.scrollWidth > b.clientWidth + 1) {
        title.hidden = true;
        b.classList.remove('ev-chap--wide');
      }
    });
  }

  buildStrip() {
    const d = this.data;
    const mount = this.root.querySelector('[data-mount="strip"]');
    mount.innerHTML = '';

    /* chapters, widths proportional to their run duration */
    const bar = el('div', 'ev-chapbar');
    /* minmax(0, Nfr), not Nfr: a track's own content must never widen it, or a long
       chapter title would steal width from its neighbours */
    bar.style.gridTemplateColumns = d.chapters
      .map((c) => 'minmax(0,' + (c.t1 - c.t).toFixed(3) + 'fr)').join(' ');
    this.chapBtns = d.chapters.map((c) => {
      const b = el('button', 'ev-chap',
        '<span class="ev-chap-num">' + c.i + '</span>' +
        '<span class="ev-chap-title">' + esc(c.title) + '</span>');
      b.type = 'button';
      b.title = c.title + ', from ' + mmss(c.t);
      b.setAttribute('aria-label', 'Chapter ' + c.i + ', ' + c.title + ', from ' + mmss(c.t));
      b.addEventListener('click', () => this.seekRun(c.t, true));
      bar.appendChild(b);
      return b;
    });
    mount.appendChild(bar);
    this.chapBar = bar;
    this.fitChapters();
    if ('ResizeObserver' in window) {
      this.chapRO = new ResizeObserver(() => this.fitChapters());
      this.chapRO.observe(bar);
    }

    /* lanes */
    const plot = el('div', 'ev-plot');
    plot.tabIndex = 0;
    plot.setAttribute('role', 'slider');
    plot.setAttribute('aria-label', 'Run time');
    plot.setAttribute('aria-valuemin', '0');
    plot.setAttribute('aria-valuemax', this.duration.toFixed(1));
    const span = (a, b) => {
      const x = (a / this.duration) * 100;
      const w = Math.max(0, (b - a) / this.duration) * 100;
      return 'left:' + x.toFixed(4) + '%;width:' + w.toFixed(4) + '%';
    };
    LANES.forEach((lane) => {
      const rows = d.lanes[lane.key] || [];
      const row = el('div', 'ev-lane ev-lane--' + lane.key);
      row.appendChild(el('span', 'ev-lane-name', laneName(lane)));
      let html = '';
      rows.forEach((r) => {
        if (lane.kind === 'span') {
          const ok = lane.key === 'motion' ? r[3] : 1;
          html += '<i class="ev-mark" data-ok="' + ok + '" style="' + span(r[0], r[1]) + '"></i>';
        } else {
          html += '<i class="ev-mark ev-mark--point" style="left:' +
            ((r[0] / this.duration) * 100).toFixed(4) + '%"></i>';
        }
      });
      const track = el('div', 'ev-track', html);
      row.appendChild(track);
      plot.appendChild(row);
    });

    /* context tokens, as a sparkline on the same axis */
    const tok = d.tokens && d.tokens.rows ? d.tokens.rows : [];
    const ci = tok.length ? d.tokens.cols.indexOf('context_tokens') : -1;
    if (tok.length > 1 && ci >= 0) {
      const max = Math.max.apply(null, tok.map((r) => r[ci]));
      const pt = (r) => [
        (r[0] / this.duration) * 1000,
        34 - (r[ci] / max) * 30
      ];
      const line = tok.map((r) => pt(r).map((v) => v.toFixed(2)).join(',')).join(' ');
      const first = pt(tok[0]), last = pt(tok[tok.length - 1]);
      const spark = el('div', 'ev-spark');
      spark.appendChild(el('span', 'ev-lane-name', 'Context tokens'));
      spark.appendChild(el('div', null,
        '<svg viewBox="0 0 1000 34" preserveAspectRatio="none" role="img" aria-label="' +
        'Context window growing to ' + Math.round(max / 1000) + ' thousand tokens over the run">' +
        '<polygon class="ev-spark-fill" points="' +
        first[0].toFixed(2) + ',34 ' + line + ' ' + last[0].toFixed(2) + ',34"/>' +
        '<polyline class="ev-spark-line" vector-effect="non-scaling-stroke" points="' +
        line + '"/></svg>'));
      plot.appendChild(spark);
      this.tokenSeries = tok.map((r) => [r[0], r[ci]]);
      this.tokenTimes = tok.map((r) => r[0]);
    }

    this.playhead = el('div', 'ev-playhead');
    this.hoverLine = el('div', 'ev-hover');
    this.hoverLine.hidden = true;
    this.tip = el('div', 'ev-tip');
    this.tip.hidden = true;
    plot.appendChild(this.playhead);
    plot.appendChild(this.hoverLine);
    plot.appendChild(this.tip);
    mount.appendChild(plot);
    this.plot = plot;
    this.wireStrip(plot);

    /* legend, and the same numbers as text */
    if ((d.lanes.motion || []).some((r) => r[3] === 0)) {
      const legend = el('ul', 'ev-legend');
      legend.appendChild(el('li', null,
        '<span class="ev-swatch" style="background:var(--ev-motion)"></span>' +
        'A motion the robot completed'));
      legend.appendChild(el('li', null,
        '<span class="ev-swatch" style="background:var(--ev-motion-bad)"></span>' +
        'A motion that failed, and the recovery that followed it'));
      mount.appendChild(legend);
    }

    this.chapNow = el('p', 'ev-chapnow');
    mount.appendChild(this.chapNow);

    mount.appendChild(el('p', 'ev-striphelp',
      'Click or drag the strip to move through the run; with it focused, the ' +
      'arrow keys step five seconds. Lane totals are in the summary below.'));
  }

  wireStrip(plot) {
    const track = plot.querySelector('.ev-track');
    const timeAt = (clientX) => {
      const r = track.getBoundingClientRect();
      return clamp(((clientX - r.left) / r.width) * this.duration, 0, this.duration);
    };
    let dragging = false;
    plot.addEventListener('pointerdown', (e) => {
      if (e.button !== 0 && e.pointerType === 'mouse') return;
      dragging = true;
      plot.setPointerCapture(e.pointerId);
      this.seekRun(timeAt(e.clientX), true);
    });
    plot.addEventListener('pointermove', (e) => {
      const t = timeAt(e.clientX);
      if (dragging) this.seekRun(t, false);
      this.showTip(t, e.clientX);
    });
    const stop = (e) => {
      if (!dragging) return;
      dragging = false;
      try { plot.releasePointerCapture(e.pointerId); } catch (_) { /* already gone */ }
      this.pushHash();
    };
    plot.addEventListener('pointerup', stop);
    plot.addEventListener('pointercancel', stop);
    plot.addEventListener('pointerleave', () => {
      this.tip.hidden = true;
      this.hoverLine.hidden = true;
    });
    plot.addEventListener('keydown', (e) => {
      const step = { ArrowLeft: -5, ArrowRight: 5, ArrowDown: -5, ArrowUp: 5,
        PageDown: -30, PageUp: 30 }[e.key];
      if (step) { this.seekRun(this.runT + step, true); e.preventDefault(); return; }
      if (e.key === 'Home') { this.seekRun(0, true); e.preventDefault(); }
      if (e.key === 'End') { this.seekRun(this.playable, true); e.preventDefault(); }
    });
  }

  showTip(t, clientX) {
    const d = this.data;
    const here = [];
    LANES.forEach((lane) => {
      const rows = d.lanes[lane.key] || [];
      const tol = (this.duration / 260);
      const hit = rows.some((r) => (
        lane.kind === 'span' ? t >= r[0] - tol / 3 && t <= r[1] + tol / 3
          : Math.abs(r[0] - t) <= tol
      ));
      if (hit) here.push(lane.name.toLowerCase());
    });
    if (this.tokenTimes) {
      const i = lastAtOrBefore(this.tokenTimes, t);
      if (i >= 0) here.push(Math.round(this.tokenSeries[i][1] / 1000) + 'k context tokens');
    }
    const plotRect = this.plot.getBoundingClientRect();
    this.tip.innerHTML = '<b>' + mmss(t) + '</b>' + (here.length ? ' &nbsp;' + esc(here.join(', ')) : '');
    /* keep the whole card inside the strip, whichever end the pointer is at */
    const half = this.tip.offsetWidth / 2;
    const x = clamp(clientX - plotRect.left, half, Math.max(half, plotRect.width - half));
    this.tip.style.left = x + 'px';
    this.tip.style.top = '-6px';
    this.tip.hidden = false;
    this.hoverLine.style.left = ((t / this.duration) * 100).toFixed(4) + '%';
    this.hoverLine.hidden = false;
  }

  /* ---- the log rail --------------------------------------------------- */

  buildRail() {
    const d = this.data;
    const mount = this.root.querySelector('[data-mount="rail"]');
    mount.innerHTML = '';

    const head = el('div', 'ev-railhead');
    head.appendChild(el('h4', 'ev-railtitle', 'What the agent did'));
    head.appendChild(el('p', 'ev-railnote', esc(d.exposes.note)));
    this.followBtn = el('button', 'ev-follow', 'Follow the video');
    this.followBtn.type = 'button';
    this.followBtn.hidden = true;
    this.followBtn.addEventListener('click', () => {
      this.follow = true;
      this.followBtn.hidden = true;
      this.scrollRailTo(this.activeIdx, true);
    });
    head.appendChild(this.followBtn);
    mount.appendChild(head);

    /* Events that began before the recording did are explained above the list rather
       than inside it: a note is not one of the options, and a listbox whose first child
       is a group with no options is not a valid structure. */
    const preIds = new Set((d.pre_recording && d.pre_recording.events) || []);
    if (preIds.size) {
      mount.appendChild(el('p', 'ev-pre',
        '<b>' + esc(d.pre_recording.label) + '</b> ' + esc(d.pre_recording.note)));
    }

    const rail = el('ol', 'ev-rail');
    rail.setAttribute('role', 'listbox');
    rail.setAttribute('aria-label', 'Episode log, ' + d.events.length + ' entries');
    rail.tabIndex = -1;

    /* parent shell command for each robot event (±0.3 s, see viewer_notes §12) */
    const parentOf = new Map();
    const shells = d.events.filter((e) => e.type === 'run' && e.kind === 'shell' && e.t1 != null);
    d.events.filter((e) => e.type === 'robot').forEach((r) => {
      const end = r.t1 != null ? r.t1 : r.t;
      for (let i = shells.length - 1; i >= 0; i--) {
        const s = shells[i];
        if (r.t >= s.t - 0.3 && end <= s.t1 + 0.3) { parentOf.set(r.i, s.i); break; }
      }
    });

    /* A Codex command's start is reconstructed as end − duration and lands about
     * 0.14 s late (viewer_notes §12.1), so 27 of e1's robot events carry a start
     * a fraction before the shell command that issued them. Their times are left
     * exactly as the data has them; only the reading order is settled, so that a
     * command never appears above the line that ran it. */
    const byId = new Map(d.events.map((e) => [e.i, e]));
    const ordered = d.events.map((ev, k) => {
      const parent = parentOf.has(ev.i) ? byId.get(parentOf.get(ev.i)) : null;
      return {
        ev: ev,
        t: ev.t,
        i: ev.i,
        child: !!parent,
        ord: parent ? Math.max(ev.t, parent.t) : ev.t,
        k: k
      };
    }).sort((a, b) => (a.ord - b.ord) || (a.child - b.child) || (a.k - b.k));

    this.entries = [];
    ordered.forEach((e) => {
      e.node = this.renderEvent(e.ev, e.child);
      this.entries.push(e);
      rail.appendChild(e.node);
    });
    this.entryTimes = this.entries.map((e) => e.ord);
    this.activeIdx = -1;
    this.tabStop = 0;
    if (this.entries[0]) this.entries[0].node.tabIndex = 0;

    rail.addEventListener('click', (ev) => {
      const li = ev.target.closest('.ev-e');
      if (!li || ev.target.closest('button')) return;
      this.activate(Number(li.dataset.idx), true);
    });
    rail.addEventListener('keydown', (ev) => this.railKeys(ev));
    ['wheel', 'touchstart', 'pointerdown'].forEach((type) => {
      rail.addEventListener(type, () => this.unfollow(), { passive: true });
    });
    mount.appendChild(rail);
    this.rail = rail;
  }

  railKeys(ev) {
    const cur = this.entries.findIndex((e) => e.node === document.activeElement);
    if (ev.key === 'ArrowDown' || ev.key === 'ArrowUp') {
      const next = clamp((cur < 0 ? this.activeIdx : cur) + (ev.key === 'ArrowDown' ? 1 : -1),
        0, this.entries.length - 1);
      this.focusEntry(next);
      this.unfollow();
      ev.preventDefault();
    } else if (ev.key === 'Enter' || ev.key === ' ') {
      if (cur >= 0) { this.activate(cur, true); ev.preventDefault(); }
    } else if (ev.key === 'Home' || ev.key === 'End') {
      this.focusEntry(ev.key === 'Home' ? 0 : this.entries.length - 1);
      this.unfollow();
      ev.preventDefault();
    }
  }

  /** One Tab stop in the rail: the entry the reader would land on. */
  setTabStop(i) {
    if (i < 0 || i === this.tabStop || !this.entries[i]) return;
    if (this.entries[this.tabStop]) this.entries[this.tabStop].node.tabIndex = -1;
    this.entries[i].node.tabIndex = 0;
    this.tabStop = i;
  }

  focusEntry(i) {
    const e = this.entries[i];
    if (!e) return;
    this.setTabStop(i);
    e.node.focus();
  }

  unfollow() {
    if (!this.follow) return;
    this.follow = false;
    this.followBtn.hidden = false;
  }

  renderEvent(ev, isChild) {
    const li = el('li', 'ev-e ev-e--' + ev.type + (isChild ? ' ev-e--child' : ''));
    li.dataset.idx = String(this.entries.length);
    li.dataset.i = String(ev.i);
    li.id = 'ev-' + this.id + '-' + ev.i;
    li.setAttribute('role', 'option');
    li.setAttribute('aria-selected', 'false');
    li.tabIndex = -1;
    if (ev.type === 'robot') {
      li.dataset.group = ev.cmd === 'frames' ? 'capture'
        : (ev.cmd === 'move_ee' || ev.cmd === 'move_delta' || ev.cmd === 'move_joints' ||
           ev.cmd === 'home' || ev.cmd === 'gripper') ? 'motion' : 'query';
      li.dataset.ok = String(ev.ok == null ? 1 : ev.ok);
    }
    const time = el('span', 'ev-time', mmss(ev.t));
    time.setAttribute('aria-hidden', 'true');
    li.appendChild(time);
    const body = el('div', 'ev-body');
    body.appendChild(el('span', 'ev-vh', 'At ' + spoken(ev.t) + '. '));
    this.fillBody(body, ev);
    li.appendChild(body);
    return li;
  }

  fillBody(body, ev) {
    const own = ' <span class="ev-own">the agent\'s own words</span>';
    if (ev.type === 'say') {
      body.appendChild(el('p', 'ev-text ev-voice', esc(ev.text)));
      body.appendChild(el('span', 'ev-own', "the agent's own words"));
    } else if (ev.type === 'think') {
      body.appendChild(el('span', 'ev-kind', 'reasoning'));
      body.appendChild(el('p', 'ev-text ev-voice', esc(ev.text)));
    } else if (ev.type === 'final') {
      body.appendChild(el('span', 'ev-kind', 'final report'));
      body.appendChild(el('p', 'ev-final ev-voice', esc(ev.text)));
    } else if (ev.type === 'look') {
      const ids = ev.img || [];
      body.appendChild(el('span', 'ev-label',
        'Opened ' + ids.length + (ids.length === 1 ? ' image' : ' images')));
      const strip = el('div', 'ev-thumbs');
      ids.forEach((id) => strip.appendChild(this.miniThumb(id)));
      body.appendChild(strip);
    } else if (ev.type === 'run') {
      if (ev.kind === 'shell') {
        body.appendChild(el('span', 'ev-label',
          esc(ev.label) + (ev.w ? own : ' <span class="ev-own">label derived from the command</span>')));
        if (ev.cmd) body.appendChild(el('code', 'ev-cmd', esc(ev.cmd)));
      } else {
        body.appendChild(el('span', 'ev-kind', ev.kind === 'read' ? 'read file' : 'wrote file'));
        body.appendChild(el('span', 'ev-label', esc(ev.file || ev.label)));
      }
      const chips = [];
      if (ev.t1 != null && ev.t1 - ev.t >= 0.05) chips.push(num(ev.t1 - ev.t, 1) + ' s');
      if (ev.exit) chips.push('<span class="ev-chip ev-chip--bad">exit ' + ev.exit + '</span>');
      if (chips.length) body.appendChild(this.chipRow(chips));
    } else if (ev.type === 'robot') {
      body.appendChild(el('span', 'ev-label',
        '<code class="ev-cmdname">' + esc(ev.cmd) + '</code> ' + this.robotTarget(ev)));
      const chips = this.robotChips(ev);
      if (chips.length) body.appendChild(this.chipRow(chips));
      if (ev.res && ev.res.files) {
        const strip = el('div', 'ev-thumbs');
        ev.res.files.forEach((name) => {
          const im = this.imgByName.get(name);
          if (im) strip.appendChild(this.miniThumb(im.i));
        });
        if (strip.children.length) body.appendChild(strip);
      }
    }
  }

  chipRow(chips) {
    return el('div', 'ev-chips', chips
      .map((c) => (c.indexOf('<') === 0 ? c : '<span class="ev-chip">' + c + '</span>'))
      .join(''));
  }

  robotTarget(ev) {
    const t = ev.target || {};
    if (ev.cmd === 'move_ee') {
      return 'to x ' + num(t.xyz[0], 3) + ', y ' + num(t.xyz[1], 3) + ', z ' +
        num(t.xyz[2], 3) + ' m' + (t.mode ? ', ' + esc(t.mode) + ' path' : '');
    }
    if (ev.cmd === 'move_delta') {
      const d = t.dpos || [0, 0, 0];
      const parts = ['x', 'y', 'z'].map((ax, i) => (
        d[i] ? ax + ' ' + (d[i] > 0 ? '+' : '') + num(d[i], 3) + ' m' : null
      )).filter(Boolean);
      const rot = t.drot_deg ? ', rotate ' + t.drot_deg.map((v) => num(v, 1)).join(', ') + '°' : '';
      return 'by ' + (parts.join(', ') || 'nothing') + rot;
    }
    if (ev.cmd === 'gripper') return esc(t.action || '');
    if (ev.cmd === 'deproject') {
      const xyz = ev.res && ev.res.xyz;
      return esc(t.cam) + ' pixel ' + t.u + ', ' + t.v +
        (t.plane_z != null ? ' on plane z ' + num(t.plane_z, 2) : '') +
        (xyz ? ' → x ' + num(xyz[0], 3) + ', y ' + num(xyz[1], 3) + ', z ' + num(xyz[2], 3) + ' m' : '');
    }
    if (ev.cmd === 'frames') {
      const cams = t.cams ? t.cams.join(' and ') + ' only' : 'all cameras';
      const r = ev.res || {};
      return 'capture ' + (r.capture != null ? r.capture : '') + ', ' + cams;
    }
    if (ev.cmd === 'home') return 'back to the observe posture';
    if (ev.cmd === 'status') return 'is the bridge alive';
    if (ev.cmd === 'state') return 'where is the arm now';
    return '';
  }

  robotChips(ev) {
    const r = ev.res || {};
    const chips = [];
    if (r.err_mm != null) chips.push(num(r.err_mm, 1) + ' mm off');
    if (r.dur_s != null) chips.push(num(r.dur_s, 1) + ' s');
    if (r.open_mm != null) {
      chips.push('opening ' + num(r.open_mm, 1) + ' mm' +
        (r.open_frac != null ? ' (' + Math.round(r.open_frac * 100) + '%)' : ''));
    }
    if (ev.counted) chips.push('<span class="ev-chip ev-chip--counted">counted, #' + ev.n + '</span>');
    if (r.error_code) {
      chips.push('<span class="ev-chip ev-chip--bad">✕ failed: ' + esc(r.error_code) + '</span>');
    }
    return chips;
  }

  miniThumb(id) {
    const im = this.imgByIndex.get(id);
    if (!im) return el('span', '');
    if (this.gated.has(id) && !this.revealed.has(id)) {
      const b = el('button', 'ev-thumb-mini ev-thumb-mini--gated', 'hand');
      b.type = 'button';
      b.title = this.data.privacy.hand_note;
      b.setAttribute('aria-label',
        'Show this still. It is hidden because it shows a demonstrator\u2019s hand.');
      b.addEventListener('click', (e) => { e.stopPropagation(); this.reveal(id); });
      return b;
    }
    const b = el('button', 'ev-thumb-btn');
    b.type = 'button';
    const img = document.createElement('img');
    img.className = 'ev-thumb-mini';
    /* loading and decoding go on before the src: the image starts fetching the moment
       src is assigned, and a lazy hint set after that is never consulted. The explicit
       size keeps the rail from reflowing as thumbnails decode. */
    img.loading = 'lazy';
    img.decoding = 'async';
    img.width = im.s[0];
    img.height = im.s[1];
    img.src = this.thumbSrc(im, 320);
    img.alt = im.cap;
    b.appendChild(img);
    b.addEventListener('click', (e) => { e.stopPropagation(); this.viewer.openImage(this, im); });
    return b;
  }

  thumbSrc(im, w) {
    return this.imgDir + String(im.i).padStart(4, '0') + '_' + w + '.webp';
  }

  /* ---- filmstrip ------------------------------------------------------ */

  buildFilm() {
    const d = this.data;
    const mount = this.root.querySelector('[data-mount="film"]');
    mount.innerHTML = '';

    const head = el('div', 'ev-filmhead');
    head.appendChild(el('h4', 'ev-filmtitle', 'What the agent looked at'));
    const nUnopened = (d.captured_not_opened || []).length;
    head.appendChild(el('p', 'ev-filmnote',
      d.images.length + ' images, in the order the agent first opened them. ' +
      'Each one lights up at the moment it was opened. ' +
      (nUnopened ? nUnopened + ' further frames were captured and never opened. ' : '') +
      'The stills are full overhead frames, so the second arm, driven by another ' +
      'agent on its own trial, is visible in them.'));
    mount.appendChild(head);

    const list = el('ul', 'ev-film');
    this.shots = [];
    d.images.forEach((im) => {
      if (HAND_POLICY === 'hide' && this.gated.has(im.i)) return;
      const li = document.createElement('li');
      const t0 = (im.t && im.t.length) ? im.t[0] : 0;
      li.appendChild(this.shotNode(im, t0));
      list.appendChild(li);
      this.shots.push({ t: t0, im: im, li: li });
    });
    ['wheel', 'touchstart', 'pointerdown'].forEach((type) => {
      list.addEventListener(type, () => { this.filmFollow = false; }, { passive: true });
    });
    mount.appendChild(list);
    this.film = list;
    this.shotTimes = this.shots.map((s) => s.t);
  }

  shotNode(im, t0) {
    if (this.gated.has(im.i) && !this.revealed.has(im.i)) {
      const box = el('div', 'ev-gate');
      box.appendChild(el('span', null, 'Shows a demonstrator’s hand'));
      const b = el('button', 'ev-gate-show', 'Show this still');
      b.type = 'button';
      b.title = this.data.privacy.hand_note;
      b.addEventListener('click', () => this.reveal(im.i));
      box.appendChild(b);
      return box;
    }
    const btn = el('button', 'ev-shot');
    btn.type = 'button';
    btn.dataset.i = String(im.i);
    const img = document.createElement('img');
    img.loading = 'lazy';          /* before src, or the hint arrives too late */
    img.decoding = 'async';
    img.width = im.s[0];
    img.height = im.s[1];
    img.src = this.thumbSrc(im, 320);
    img.alt = im.cap;
    btn.appendChild(img);
    if (im.made) btn.appendChild(el('span', 'ev-shot-made', 'agent made this'));
    btn.appendChild(el('span', 'ev-shot-cap',
      '<span class="ev-shot-time">' + mmss(t0) + '</span>' + esc(im.cap)));
    btn.addEventListener('click', () => this.viewer.openImage(this, im));
    return btn;
  }

  /** Reveal one privacy-gated still, everywhere it appears. */
  reveal(id) {
    this.revealed.add(id);
    const im = this.imgByIndex.get(id);
    const shot = this.shots.find((s) => s.im.i === id);
    if (shot) {
      shot.li.innerHTML = '';
      shot.li.appendChild(this.shotNode(im, shot.t));
    }
    this.rail.querySelectorAll('.ev-thumb-mini--gated').forEach((b) => {
      const li = b.closest('.ev-e');
      const ev = li && this.entries[Number(li.dataset.idx)].ev;
      if (ev && ev.img && ev.img.indexOf(id) >= 0) {
        b.replaceWith(this.miniThumb(id));
      }
    });
    this.paintShots(this.runT, true);
  }

  /* ---- playback ------------------------------------------------------- */

  togglePlay() {
    this.viewer.touched = true;
    if (this.video.paused) {
      if (this.video.currentTime >= this.maxVideoT - 0.05) this.video.currentTime = 0;
      const p = this.video.play();
      if (p && p.catch) p.catch(() => { /* a blocked play leaves the poster up */ });
    } else {
      this.video.pause();
    }
  }

  onPlay() {
    this.playBtn.textContent = 'Pause';
    document.dispatchEvent(new CustomEvent('agp:viewer-play', { detail: { id: this.id } }));
    this.viewer.pauseOthers(this);
    const loop = () => {
      if (this.video.paused) return;
      this.tick(false);
      this.rafId = requestAnimationFrame(loop);
    };
    cancelAnimationFrame(this.rafId);
    this.rafId = requestAnimationFrame(loop);
  }

  onPause() {
    this.playBtn.textContent = 'Play';
    cancelAnimationFrame(this.rafId);
    this.rafId = 0;
    this.tick(true);
    this.pushHash();
  }

  pause() { if (!this.video.paused) this.video.pause(); }

  /** Seek on the run clock. Converts once, here, and nowhere else. */
  seekRun(t, andHash) {
    if (andHash) this.viewer.touched = true;
    const run = clamp(t, 0, this.playable);
    const v = clamp(this.runToVideo(run), 0, Math.max(0, this.maxVideoT - 0.02));
    this.warm();
    this.video.currentTime = v;
    this.runT = run;
    this.tick(true);
    if (andHash) this.pushHash();
  }

  /** preload="none" keeps the 14 MB clip off the wire until it is wanted; the
   *  first seek or the section coming into view starts the metadata fetch, so
   *  that seeking paints a frame instead of leaving the poster up. */
  warm() {
    if (this.warmed) return;
    this.warmed = true;
    if (this.video.preload === 'none') this.video.preload = 'metadata';
    if (this.video.readyState === 0) this.video.load();
  }

  setCaptions(on) {
    this.captionsOn = on;
    const tracks = this.video.textTracks || [];
    for (let i = 0; i < tracks.length; i++) {
      if (tracks[i].kind === 'captions' || tracks[i].kind === 'subtitles') {
        tracks[i].mode = on ? 'showing' : 'hidden';
      } else if (tracks[i].kind === 'chapters') {
        tracks[i].mode = 'hidden';
      }
    }
    if (this.capBtn) {
      this.capBtn.textContent = on ? 'Captions on' : 'Captions off';
      this.capBtn.setAttribute('aria-pressed', on ? 'true' : 'false');
    }
  }

  /** One frame of synchronisation: playhead, clock, chapter, rail, filmstrip. */
  tick(force) {
    const run = this.videoToRun(this.video.currentTime || 0);
    if (!force && Math.abs(run - this.runT) < 0.02) return;
    this.runT = run;

    const pct = clamp(run / this.duration, 0, 1) * 100;
    this.playhead.style.left = pct.toFixed(4) + '%';
    this.plot.setAttribute('aria-valuenow', run.toFixed(1));
    this.plot.setAttribute('aria-valuetext', spoken(run) + ' of ' + spoken(this.duration));
    this.clock.innerHTML = '<b>' + mmss(run) + '</b> / ' + mmss(this.duration) +
      '<span class="ev-clock-unit"> of the run</span>';

    const ch = this.data.chapters.findIndex((c) => run >= c.t && run < c.t1);
    this.chapBtns.forEach((b, i) => b.setAttribute('aria-current', i === ch ? 'true' : 'false'));
    if (ch !== this.lastChapter) {
      this.lastChapter = ch;
      const c = this.data.chapters[ch < 0 ? this.data.chapters.length - 1 : ch];
      this.chapNow.innerHTML = '<span class="ev-chapnow-n">Chapter ' + c.i + ' of ' +
        this.data.chapters.length + '</span>' + esc(c.title);
    }

    const idx = lastAtOrBefore(this.entryTimes, run);
    if (idx !== this.activeIdx) {
      if (this.activeIdx >= 0) {
        this.entries[this.activeIdx].node.setAttribute('aria-selected', 'false');
      }
      this.activeIdx = idx;
      if (idx >= 0) {
        const node = this.entries[idx].node;
        node.setAttribute('aria-selected', 'true');
        if (!this.rail.contains(document.activeElement)) this.setTabStop(idx);
        if (this.follow) this.scrollRailTo(idx, false);
      }
    }
    this.paintShots(run, force);
  }

  paintShots(run, force) {
    if (!this.shots) return;
    const i = lastAtOrBefore(this.shotTimes, run);
    if (!force && i === this.lastShot) return;
    this.lastShot = i;
    this.shots.forEach((s, k) => {
      const btn = s.li.firstElementChild;
      if (!btn || !btn.dataset) return;
      btn.dataset.seen = k <= i ? '1' : '0';
      btn.dataset.current = k === i ? '1' : '0';
    });
    if (i >= 0 && this.filmFollow) {
      const li = this.shots[i].li;
      const want = li.offsetLeft - this.film.clientWidth / 2 + li.offsetWidth / 2;
      this.film.scrollTo({ left: Math.max(0, want), behavior: reduceMotion.matches ? 'auto' : 'smooth' });
    }
  }

  scrollRailTo(idx, userAsked) {
    if (idx < 0) return;
    const node = this.entries[idx].node;
    const want = node.offsetTop - this.rail.clientHeight / 2 + node.offsetHeight / 2;
    this.rail.scrollTo({
      top: Math.max(0, want),
      behavior: reduceMotion.matches || !userAsked ? 'auto' : 'smooth'
    });
  }

  /** Click a log entry: seek there and select it. */
  activate(idx, andHash) {
    const e = this.entries[idx];
    if (!e) return;
    if (andHash) this.viewer.touched = true;
    this.follow = true;
    this.followBtn.hidden = true;
    /* seek to the entry's ordering time: for the few robot commands whose
     * reconstructed start sits a fraction before the line that issued them,
     * that is the parent's start, which keeps the rail's selection and the
     * playhead on the same entry. At most 0.15 s, two frames. */
    this.seekRun(e.ord != null ? e.ord : e.t, false);
    if (andHash) this.pushHash(e.i);
    if (e.ev.type === 'look' && e.ev.img && e.ev.img.length) {
      const im = this.imgByIndex.get(e.ev.img[0]);
      if (im && this.filmFollow) this.paintShots(this.runT, true);
    }
  }

  step(dir) {
    const next = clamp((this.activeIdx < 0 ? 0 : this.activeIdx + dir), 0, this.entries.length - 1);
    this.activate(next, true);
    this.focusEntry(next);
  }

  hash(i) {
    return '#' + this.id + '&t=' + this.runT.toFixed(1) + (i != null ? '&i=' + i : '');
  }

  pushHash(i) {
    if (!this.viewer.touched) return;
    try {
      history.replaceState(null, '', this.hash(i));
    } catch (_) { /* file:// and sandboxed frames refuse; not worth reporting */ }
  }

  copyLink(btn) {
    const url = location.href.split('#')[0] + this.hash();
    const done = (ok) => {
      const was = btn.innerHTML;
      btn.textContent = ok ? 'Link copied' : url;
      setTimeout(() => { btn.innerHTML = was; }, 2400);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(url).then(() => done(true), () => done(false));
    } else {
      done(false);
    }
  }
}

/* ── the viewer: two episodes, one at a time ────────────────────────────── */

class Viewer {
  constructor(root) {
    this.root = root;
    this.touched = false;
    this.started = false;
    this.episodes = Array.from(root.querySelectorAll('.ev-ep'))
      .map((a) => new Episode(a, this));
    this.current = null;
    this.root.classList.add('ev--js');
    this.buildPicker();
    this.buildLightbox();

    /* The page's "Pause clips" control stops the clips autoplay.js owns and dispatches
     * this; the viewer's video is not one of those (it has no data-autoplay and never
     * starts by itself), so this event is the whole of the coupling in that direction.
     * The other direction is agp:viewer-play, which autoplay.js listens for. */
    document.addEventListener('agp:pause-all', () => this.pauseAll());

    /* leaving the tab should not cost the reader their place in a 15-minute run */
    document.addEventListener('visibilitychange', () => {
      if (document.hidden) this.pauseAll();
    });
    window.addEventListener('hashchange', () => this.fromHash());
    document.addEventListener('keydown', (e) => this.keys(e));

    /* Section 12 sits about three quarters of the way down a 470 KB page. Showing the
     * chosen episode costs nothing, but loading its timeline is a 60 KB fetch that
     * builds a 150-entry log, a six-lane strip and a 37-image filmstrip, so that part
     * waits until the section is first approached. A deep link to an episode skips the
     * wait. */
    const want = this.parseHash();
    this.show(want ? want.id : this.episodes[0].id, false);

    if ('IntersectionObserver' in window) {
      const io = new IntersectionObserver((entries) => {
        entries.forEach((en) => {
          this.visible = en.isIntersecting;
          if (en.isIntersecting) {
            if (!this.started) this.start();
            else if (this.current && this.current.built) this.current.warm();
          } else if (this.current) {
            this.current.pause();
          }
        });
      }, { threshold: 0, rootMargin: '400px 0px' });
      io.observe(root);
    } else {
      this.visible = true;
    }

    if (want || !('IntersectionObserver' in window)) {
      this.start().then(() => { if (want) this.applyHash(want); });
    }
  }

  buildPicker() {
    const mount = this.root.querySelector('[data-mount="picker"]');
    mount.innerHTML = '';
    mount.appendChild(el('span', 'ev-picker-label', 'Two runs of the same task'));
    /* Two plain buttons, and announced as two plain buttons. They were a role="tablist"
       with aria-selected, which promises tabpanel semantics and arrow-key movement that
       this widget does not implement. */
    const tabs = el('div', 'ev-tabs');
    tabs.setAttribute('role', 'group');
    tabs.setAttribute('aria-label', 'Choose an episode');
    this.tabs = this.episodes.map((ep, i) => {
      const title = ep.root.querySelector('.ev-ep-title').textContent;
      const b = el('button', 'ev-tab',
        esc(title.split(',')[0]) + '<span class="ev-tab-key">' + (i + 1) + '</span>');
      b.type = 'button';
      b.setAttribute('aria-pressed', 'false');
      b.title = title;
      b.addEventListener('click', () => { this.touched = true; this.select(ep.id, true); });
      tabs.appendChild(b);
      return b;
    });
    mount.appendChild(tabs);
  }

  buildLightbox() {
    const dlg = document.createElement('dialog');
    dlg.className = 'ev-lightbox';
    dlg.innerHTML =
      '<img class="ev-lb-img" alt="">' +
      '<div class="ev-lb-foot">' +
      '<div class="ev-lb-textcol"><p class="ev-lb-cap"></p><p class="ev-lb-meta"></p></div>' +
      '<button type="button" class="ev-btn" data-act="seek">Go to this moment</button>' +
      '<button type="button" class="ev-btn" data-act="close">Close</button>' +
      '</div>';
    dlg.addEventListener('click', (e) => {
      const act = e.target.dataset && e.target.dataset.act;
      if (act === 'close' || e.target === dlg) this.closeImage();
      if (act === 'seek' && this.lbEpisode && this.lbImage) {
        const t = (this.lbImage.t && this.lbImage.t.length) ? this.lbImage.t[0] : 0;
        this.closeImage();
        this.lbEpisode.seekRun(t, true);
      }
    });
    /* inside the viewer root, not on <body>: the dialog reads the --ev-*
     * variables declared on .ev, and showModal still lifts it to the top layer */
    this.root.appendChild(dlg);
    this.lightbox = dlg;
  }

  openImage(ep, im) {
    if (ep.gated.has(im.i) && !ep.revealed.has(im.i)) { ep.reveal(im.i); return; }
    const dlg = this.lightbox;
    this.lbEpisode = ep;
    this.lbImage = im;
    const img = dlg.querySelector('.ev-lb-img');
    img.src = ep.thumbSrc(im, 960);
    img.alt = im.cap;
    img.width = im.m[0];
    img.height = im.m[1];
    dlg.querySelector('.ev-lb-cap').textContent = im.cap;
    const bits = [];
    if (im.t && im.t.length) bits.push('opened at ' + mmss(im.t[0]));
    if (im.ct != null) bits.push('captured at ' + mmss(im.ct));
    bits.push(im.m[0] + ' × ' + im.m[1] + ' shown');
    if (im.made) bits.push('the agent made this image itself');
    dlg.querySelector('.ev-lb-meta').textContent = bits.join(', ');
    if (dlg.showModal) dlg.showModal(); else dlg.setAttribute('open', '');
  }

  closeImage() {
    const dlg = this.lightbox;
    if (dlg.close) dlg.close(); else dlg.removeAttribute('open');
    this.lbImage = null;
  }

  /** Show one episode. Markup only: no fetch, no build. */
  show(id, focus) {
    const ep = this.episodes.find((e) => e.id === id) || this.episodes[0];
    if (this.current !== ep) {
      this.episodes.forEach((other) => {
        if (other !== ep) { other.pause(); other.root.hidden = true; }
      });
      ep.root.hidden = false;
      this.current = ep;
      this.tabs.forEach((b, i) => {
        b.setAttribute('aria-pressed', this.episodes[i] === ep ? 'true' : 'false');
      });
      if (focus) {
        ep.root.querySelector('.ev-ep-title').scrollIntoView({
          block: 'nearest', behavior: reduceMotion.matches ? 'auto' : 'smooth'
        });
      }
    }
    return ep;
  }

  /** Load and build the episode on screen. Called on the first approach, and by any
   *  action that needs the timeline. */
  start() {
    this.started = true;
    return this.select(this.current.id, false);
  }

  /** Show one episode, load its timeline once, and resolve when it is built. */
  async select(id, focus) {
    const ep = this.show(id, focus);
    this.started = true;
    if (!ep.ready) {
      ep.ready = ep.load().then(() => ep.build()).catch(() => this.degrade(ep));
    }
    await ep.ready;
    if (ep.built) { ep.fitChapters(); if (this.visible) ep.warm(); }
    return ep;
  }

  /** The timeline did not load: keep the video, its captions and the summary. */
  degrade(ep) {
    ep.root.querySelector('[data-mount="rail"]').innerHTML =
      '<p class="ev-note">The log for this episode could not be loaded. The video, ' +
      'its captions and the written summary below still describe the run.</p>';
    ep.root.querySelectorAll('[data-js-hide]')
      .forEach((n) => n.removeAttribute('data-js-hide'));
  }

  pauseOthers(keep) {
    this.episodes.forEach((e) => { if (e !== keep) e.pause(); });
  }

  pauseAll() {
    this.episodes.forEach((e) => e.pause());
  }

  /** #e1&t=123.4&i=105 — episode id first, then key=value pairs. */
  parseHash() {
    const raw = (location.hash || '').replace(/^#/, '');
    if (!raw) return null;
    const parts = raw.split('&');
    const id = parts[0];
    if (!this.episodes.some((e) => e.id === id)) return null;
    const out = { id: id };
    parts.slice(1).forEach((p) => {
      const [k, v] = p.split('=');
      if (k === 't') out.t = parseFloat(v);
      if (k === 'i') out.i = parseInt(v, 10);
    });
    return out;
  }

  fromHash() {
    const want = this.parseHash();
    if (!want) return null;
    this.select(want.id, false).then(() => this.applyHash(want));
    return want.id;
  }

  applyHash(want) {
    const ep = this.episodes.find((e) => e.id === want.id);
    if (!ep || !ep.built) return;
    if (want.i != null && !Number.isNaN(want.i)) {
      const idx = ep.entries.findIndex((e) => e.i === want.i);
      if (idx >= 0) { ep.activate(idx, false); return; }
    }
    if (want.t != null && !Number.isNaN(want.t)) ep.seekRun(want.t, false);
  }

  keys(e) {
    if (e.defaultPrevented || e.metaKey || e.ctrlKey || e.altKey) return;
    const t = e.target;
    if (t && (t.isContentEditable ||
      /^(input|textarea|select|option)$/i.test(t.tagName || ''))) return;
    /* WCAG 2.1.4: these are unmodified single-character shortcuts, so they fire only
       while focus is genuinely inside this component. Taking Space from the document
       body stops the page scrolling as soon as the section scrolls into view, on a
       document that is 69,000 px tall. */
    if (!this.root.contains(t)) return;
    const ep = this.current;
    if (!ep || !ep.built) return;
    if (e.key === ' ' || e.key === 'Spacebar') {
      if (t && t.closest && t.closest('button, [role="option"], [role="slider"]')) return;
      this.touched = true; ep.togglePlay(); e.preventDefault();
    } else if (e.key === 'j') {
      this.touched = true; ep.step(-1); e.preventDefault();
    } else if (e.key === 'k') {
      this.touched = true; ep.step(1); e.preventDefault();
    } else if (e.key === '1' || e.key === '2') {
      const target = this.episodes[Number(e.key) - 1];
      if (target) { this.touched = true; this.select(target.id, true); e.preventDefault(); }
    } else if (e.key === 'Escape' && this.lightbox.open) {
      this.closeImage();
    }
  }
}

/* ── boot ───────────────────────────────────────────────────────────────── */

function boot() {
  const root = document.querySelector('[data-agp-viewer]');
  if (!root || root.dataset.booted) return;
  root.dataset.booted = '1';
  return new Viewer(root);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot, { once: true });
} else {
  boot();
}

export { boot };
